USE onyourway;

-- User
CREATE TABLE IF NOT EXISTS USERS (
  username VARCHAR(15),
  usr_pass VARCHAR(15) NOT NULL,
  fname	VARCHAR(15) NOT NULL,
  lname VARCHAR(15) NOT NULL,
  PRIMARY KEY (username)
);

-- Friends
CREATE TABLE IF NOT EXISTS FRIENDS (
  userid VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  friendid VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (userid, friendid)
);

-- Routes
CREATE TABLE IF NOT EXISTS ROUTE (
  routeid INT(15),
  rname VARCHAR(15),
  -- routinginfo UNKNOWN(999999),
  ownerid VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (routeid)
);

-- Group
CREATE TABLE IF NOT EXISTS GROUPS (
  groupid INT(15),
  gname VARCHAR(15),
  ownerID VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (groupid)
);

-- Group Members
CREATE TABLE IF NOT EXISTS GROUP_MEMBERS (
  groupid INT(15)
  	REFERENCES GROUPS(groupid)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  userid VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (groupid, userid)
);

-- User-Route Access
CREATE TABLE IF NOT EXISTS USER_ROUTE_ACCESS (
  userid VARCHAR(15)
  	REFERENCES USERS(username)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  routeid INT(15)
  	REFERENCES ROUTE(routeid)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  modrights CHAR(1),
  PRIMARY KEY (userid, routeid)
);

-- Group Route Access
CREATE TABLE IF NOT EXISTS GROUP_ROUTE_ACCESS (
  groupid INT(15)
  	REFERENCES GROUPS(groupid)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  routeid INT(15)
  	REFERENCES ROUTE(routeid)
  	ON UPDATE CASCADE ON DELETE CASCADE,
  PRIMARY KEY (groupid, routeid)
);
